#%RAML 1.0 DataType

type: object
displayName: Employment
properties:
  industry:
    type: string
    example: "Computer Software"
    description: |
      Industry sector.
  company:
    type: string
    example: "Fico"
    description: |
      Employer company.
  tenure:
    type: string
    example: "7 years"
    description: |
      Tenure.
